<?xml version="1.0" encoding="UTF-8"?>
<Project>
    <Project_Created_Time>2018-01-15 17:48:49</Project_Created_Time>
    <TD_Version>4.1.033</TD_Version>
    <UCode>0011110010000111</UCode>
    <Name>e203egmini_new</Name>
    <HardWare>
        <Family>EG4</Family>
        <Device>EG4S20BG256</Device>
    </HardWare>
    <Source_Files>
        <Verilog>
            <File>../src/config.v</File>
            <File>../src/e203_biu.v</File>
            <File>../src/e203_clk_ctrl.v</File>
            <File>../src/e203_clkgate.v</File>
            <File>../src/e203_core.v</File>
            <File>../src/e203_cpu.v</File>
            <File>../src/e203_cpu_top.v</File>
            <File>../src/e203_defines.v</File>
            <File>../src/e203_dtcm_ctrl.v</File>
            <File>../src/e203_dtcm_ram.v</File>
            <File>../src/e203_extend_csr.v</File>
            <File>../src/e203_exu.v</File>
            <File>../src/e203_exu_alu.v</File>
            <File>../src/e203_exu_alu_bjp.v</File>
            <File>../src/e203_exu_alu_csrctrl.v</File>
            <File>../src/e203_exu_alu_dpath.v</File>
            <File>../src/e203_exu_alu_lsuagu.v</File>
            <File>../src/e203_exu_alu_muldiv.v</File>
            <File>../src/e203_exu_alu_rglr.v</File>
            <File>../src/e203_exu_branchslv.v</File>
            <File>../src/e203_exu_commit.v</File>
            <File>../src/e203_exu_csr.v</File>
            <File>../src/e203_exu_decode.v</File>
            <File>../src/e203_exu_disp.v</File>
            <File>../src/e203_exu_excp.v</File>
            <File>../src/e203_exu_longpwbck.v</File>
            <File>../src/e203_exu_oitf.v</File>
            <File>../src/e203_exu_regfile.v</File>
            <File>../src/e203_exu_wbck.v</File>
            <File>../src/e203_ifu.v</File>
            <File>../src/e203_ifu_ifetch.v</File>
            <File>../src/e203_ifu_ift2icb.v</File>
            <File>../src/e203_ifu_litebpu.v</File>
            <File>../src/e203_ifu_minidec.v</File>
            <File>../src/e203_irq_sync.v</File>
            <File>../src/e203_itcm_ctrl.v</File>
            <File>../src/e203_itcm_ram.v</File>
            <File>../src/e203_lsu.v</File>
            <File>../src/e203_lsu_ctrl.v</File>
            <File>../src/e203_reset_ctrl.v</File>
            <File>../src/e203_soc_top.v</File>
            <File>../src/e203_srams.v</File>
            <File>../src/e203_subsys_clint.v</File>
            <File>../src/e203_subsys_gfcm.v</File>
            <File>../src/e203_subsys_hclkgen.v</File>
            <File>../src/e203_subsys_hclkgen_rstsync.v</File>
            <File>../src/e203_subsys_main.v</File>
            <File>../src/e203_subsys_mems.v</File>
            <File>../src/e203_subsys_perips.v</File>
            <File>../src/e203_subsys_plic.v</File>
            <File>../src/e203_subsys_pll.v</File>
            <File>../src/e203_subsys_pllclkdiv.v</File>
            <File>../src/e203_subsys_top.v</File>
            <File>../src/i2c_master_bit_ctrl.v</File>
            <File>../src/i2c_master_byte_ctrl.v</File>
            <File>../src/i2c_master_defines.v</File>
            <File>../src/i2c_master_top.v</File>
            <File>../src/iobuf.v</File>
            <File>../src/reset_sys.v</File>
            <File>../src/sirv_1cyc_sram_ctrl.v</File>
            <File>../src/sirv_aon.v</File>
            <File>../src/sirv_aon_lclkgen_regs.v</File>
            <File>../src/sirv_aon_porrst.v</File>
            <File>../src/sirv_aon_top.v</File>
            <File>../src/sirv_aon_wrapper.v</File>
            <File>../src/sirv_AsyncResetReg.v</File>
            <File>../src/sirv_AsyncResetRegVec.v</File>
            <File>../src/sirv_AsyncResetRegVec_1.v</File>
            <File>../src/sirv_AsyncResetRegVec_36.v</File>
            <File>../src/sirv_AsyncResetRegVec_67.v</File>
            <File>../src/sirv_AsyncResetRegVec_129.v</File>
            <File>../src/sirv_clint.v</File>
            <File>../src/sirv_clint_top.v</File>
            <File>../src/sirv_debug_csr.v</File>
            <File>../src/sirv_debug_module.v</File>
            <File>../src/sirv_debug_ram.v</File>
            <File>../src/sirv_debug_rom.v</File>
            <File>../src/sirv_DeglitchShiftRegister.v</File>
            <File>../src/sirv_expl_apb_slv.v</File>
            <File>../src/sirv_expl_axi_slv.v</File>
            <File>../src/sirv_flash_qspi.v</File>
            <File>../src/sirv_flash_qspi_top.v</File>
            <File>../src/sirv_gnrl_bufs.v</File>
            <File>../src/sirv_gnrl_dffs.v</File>
            <File>../src/sirv_gnrl_icbs.v</File>
            <File>../src/sirv_gnrl_ram.v</File>
            <File>../src/sirv_gnrl_xchecker.v</File>
            <File>../src/sirv_gpio.v</File>
            <File>../src/sirv_gpio_top.v</File>
            <File>../src/sirv_hclkgen_regs.v</File>
            <File>../src/sirv_icb1to2_bus.v</File>
            <File>../src/sirv_icb1to8_bus.v</File>
            <File>../src/sirv_icb1to16_bus.v</File>
            <File>../src/sirv_jtag_dtm.v</File>
            <File>../src/sirv_jtaggpioport.v</File>
            <File>../src/sirv_LevelGateway.v</File>
            <File>../src/sirv_mrom.v</File>
            <File>../src/sirv_mrom_top.v</File>
            <File>../src/sirv_otp_top.v</File>
            <File>../src/sirv_plic_man.v</File>
            <File>../src/sirv_plic_top.v</File>
            <File>../src/sirv_pmu.v</File>
            <File>../src/sirv_pmu_core.v</File>
            <File>../src/sirv_pwm8.v</File>
            <File>../src/sirv_pwm8_core.v</File>
            <File>../src/sirv_pwm8_top.v</File>
            <File>../src/sirv_pwm16.v</File>
            <File>../src/sirv_pwm16_core.v</File>
            <File>../src/sirv_pwm16_top.v</File>
            <File>../src/sirv_pwmgpioport.v</File>
            <File>../src/sirv_qspi_1cs.v</File>
            <File>../src/sirv_qspi_1cs_top.v</File>
            <File>../src/sirv_qspi_4cs.v</File>
            <File>../src/sirv_qspi_4cs_top.v</File>
            <File>../src/sirv_qspi_arbiter.v</File>
            <File>../src/sirv_qspi_fifo.v</File>
            <File>../src/sirv_qspi_media.v</File>
            <File>../src/sirv_qspi_media_1.v</File>
            <File>../src/sirv_qspi_media_2.v</File>
            <File>../src/sirv_qspi_physical.v</File>
            <File>../src/sirv_qspi_physical_1.v</File>
            <File>../src/sirv_qspi_physical_2.v</File>
            <File>../src/sirv_queue.v</File>
            <File>../src/sirv_queue_1.v</File>
            <File>../src/sirv_repeater_6.v</File>
            <File>../src/sirv_ResetCatchAndSync.v</File>
            <File>../src/sirv_ResetCatchAndSync_2.v</File>
            <File>../src/sirv_rtc.v</File>
            <File>../src/sirv_sim_ram.v</File>
            <File>../src/sirv_spi_flashmap.v</File>
            <File>../src/sirv_spigpioport.v</File>
            <File>../src/sirv_spigpioport_1.v</File>
            <File>../src/sirv_spigpioport_2.v</File>
            <File>../src/sirv_sram_icb_ctrl.v</File>
            <File>../src/sirv_tl_repeater_5.v</File>
            <File>../src/sirv_tlfragmenter_qspi_1.v</File>
            <File>../src/sirv_tlwidthwidget_qspi.v</File>
            <File>../src/sirv_uart.v</File>
            <File>../src/sirv_uart_top.v</File>
            <File>../src/sirv_uartgpioport.v</File>
            <File>../src/sirv_uartrx.v</File>
            <File>../src/sirv_uarttx.v</File>
            <File>../src/sirv_wdog.v</File>
            <File>../src/system.v</File>
            <File>al_ip/bram.v</File>
            <File>al_ip/pll.v</File>
            <File>../src/clkdivider.v</File>
            <File>al_ip/bram_32.v</File>
        </Verilog>
        <ADC_FILE>../constraint/io_cst.adc</ADC_FILE>
        <SDC_FILE>e203egmini_new.sdc</SDC_FILE>
        <CWC_FILE/>
    </Source_Files>
    <TOP_MODULE>
        <LABEL/>
        <MODULE>system</MODULE>
        <CREATEINDEX>auto</CREATEINDEX>
    </TOP_MODULE>
    <Property>
        <RouteProperty>
            <effort>high</effort>
        </RouteProperty>
    </Property>
    <Project_Settings>
        <Step_Last_Change>2018-06-27 15:22:30</Step_Last_Change>
        <Current_Step>60</Current_Step>
        <Step_Status>true</Step_Status>
    </Project_Settings>
</Project>
