/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/DELL/Desktop/e203egmini_new/project/al_ip/bram_32.v
 ** Date	:	2018 01 15
 ** TD version	:	4.0.972
\************************************************************/

`timescale 1ns / 1ps

module bram_32 ( doa, dia, addra, cea, clka, wea, rsta );

	output [31:0] doa;

	input  [31:0] dia;
	input  [13:0] addra;
	input  [3:0] wea;
	input  cea;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.ADDR_WIDTH_A(14),
				.DATA_DEPTH_A(16384),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_B(14),
				.DATA_DEPTH_B(16384),
				.BYTE_ENABLE(8),
				.BYTE_A(4),
				.BYTE_B(4),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb({14{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.bea(wea),
				.web(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule