/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/DELL/Desktop/e203egmini_new/project/al_ip/bram.v
 ** Date	:	2018 01 15
 ** TD version	:	4.0.972
\************************************************************/

`timescale 1ns / 1ps

module bram ( 
	doa, dia, addra, cea, clka, wea, rsta, 
	dob, dib, addrb, ceb, clkb, web, rstb
);

	output [63:0] doa;
	output [63:0] dob;


	input  [63:0] dia;
	input  [63:0] dib;
	input  [12:0] addra;
	input  [12:0] addrb;
	input  [7:0] wea;
	input  [7:0] web;
	input  cea;
	input  ceb;
	input  clka;
	input  clkb;
	input  rsta;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(64),
				.DATA_WIDTH_B(64),
				.ADDR_WIDTH_A(13),
				.ADDR_WIDTH_B(13),
				.DATA_DEPTH_A(8192),
				.DATA_DEPTH_B(8192),
				.BYTE_ENABLE(8),
				.BYTE_A(8),
				.BYTE_B(8),
				.MODE("DP"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("32K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib(dib),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b0),
				.bea(wea),
				.web(1'b0),
				.beb(web),
				.rsta(rsta),
				.rstb(rstb),
				.doa(doa),
				.dob(dob));


endmodule